[version]
source = "regex"
scheme = "standard"
path = "src/captchafox/__init__.py"

[build]
reproducible = true
directory = "dist"
dev-mode-dirs = ["src"]

[envs.virtual]
python = "3.12"
platforms = ["linux", "windows"]

[tool.hatch.metadata]
allow-direct-references = true
allow-ambiguous-features = true
